### ISSUE TITLE
rlev2 crash reading PATCHED_BASE

### ISSUE THREAD

**Issue by swalkaus** [hortonworks/orc#109]
Length of the patch list is zero leading to crash

**Comment by asandryh** [comment]
I'm about to push a fix for DIRECT and DELTA encodings. Do you want to see if this also fixes your problem?


On 02/11/2015 10:31 PM, Stephen Walkauskas wrote:

Length of the patch list is zero leading to crash

�

**Comment by asandryh** [comment]
Take a look at my commit:
https://github.com/hortonworks/orc/commit/cba104ac69787d573a937a8a0474fe79e249fca9

The fix was adding two lines to RLEv2.cc. It took me almost the entire day today to chase them down, though... :(

Some of the RLEv2 tests for DIRECT encoding are not working now. I commented them out and created an issue to fix them. Let me know if you want to take care of them; otherwise I'll do this when I get a chance.


On 02/11/2015 11:15 PM, Sandryhaila, Aliaksei wrote:
I'm about to push a fix for DIRECT and DELTA encodings. Do you want to see if this also fixes your problem?


On 02/11/2015 10:31 PM, Stephen Walkauskas wrote:

Length of the patch list is zero leading to crash

�
