### ISSUE TITLE
Revisit the use of long data type

### ISSUE THREAD

**Issue by thanhdowisc** [hortonworks/orc#134]
Hi folks,

We should revisit the places where **long** data type is used. In posix, **long** is 4 bytes in 32 bit architecture and 8 bytes in 64 bit. However, in Windows, **long** is 4 bytes no matter what. Because of this, compilation in Windows could finish successfully, but some tests will fail. Additionally compilation in windows will generate many warnings such as "conversion from '**uint64_t**' to '**unsigned long**', possible loss of data"

We should stick with using int64_t or uint64_t instead.

Any comments?

**Comment by asandryh** [comment]
+1
We can also use size_t for unsigned types, where appropriate (such as loop iterators). Will this be ok with Windows?


On 2/27/2015 1:46 AM, Thanh Do wrote:

Hi folks,

We should revisit the places where long data type is used. In posix, long is 4 bytes in 32 bit architecture and 8 bytes in 64 bit. However, in Windows, long is 4 bytes no matter what. Because of this, compilation in Windows could finish successfully, but some tests will fail. Additionally compilation in windows will generate many warnings such as "conversion from 'uint64_t' to 'unsigned long', possible loss of data"

We should stick with using int64_t or uint64_t instead.

Any comments?

�

**Comment by swalkaus** [comment]
I suggest we use uint64_t and int64_t everywhere except in the rare cases that a 4-byte value is needed (e.g. for storage).

**Comment by omalley** [comment]
The more I use C++ going with uint64_t and int64_t seem right. Trying to use size_t and streamoff get pretty confusing. This is a more complete version of #49.

**Comment by thanhdowisc** [comment]
Cool! Let's stick to this plan for any new code that we add. 

For old code, we should make a pull request. Anybody want to make a crack on this?

I am currently working on #121, trying to make all the tests pass in Windows. There are 6 tests fail, very likely due to this reason.

**Comment by thanhdowisc** [comment]
size_t for unsigned type in loop operators should not be a problem in Windows
