### ISSUE TITLE
ORC timestamp columns are sensitive to moving between timezones

### ISSUE THREAD

**Issue by omalley** [hortonworks/orc#170]
See https://issues.apache.org/jira/browse/HIVE-8746

ORC stores the difference from an epoch in the local timezone. That makes ORC mostly resilient when moving between timezones, but fails when moving between timezones with different daylight savings rules.

ORC currently stores the timezone information in the stripe footer, so that the reader can understand the times correctly.

**Comment by thanhdowisc** [comment]
A follow up question, suppose I want to get the timezone information so that I can interpret a timestamp value correctly, what is the most efficient way to do this?

One way I think of is following what is written in FileMetadata (get the footer, then get the timezone) but I found this cumbersome. Any thought?

**Comment by omalley** [comment]
We need to include a library that understands timezones and uses the timezone information from the writer to interpret the timestamp information correctly regardless of the local timezone.

**Comment by omalley** [comment]
Moved to Apache as ORC-10.
